### ISSUE TITLE
Write validators for the webpack API

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/webpack-validator#1]
I need help writing validators. Please see [CONTRIBUTING.md](https://github.com/kentcdodds/webpack-validator/blob/master/CONTRIBUTING.md) file to find out how. Also check out [configuration-validator documentation](https://github.com/kentcdodds/configuration-validator) to see what a validator looks like.

I really need feedback on the API. Everything's in beta right now so we can mess around with the API as much as we want (rename things, restructure things, etc. etc.).

**Comment by kentcdodds** [comment]
I'm currently working on the `entry` property :-)

**Comment by kentcdodds** [comment]
`entry` has now been implemented. Validates that the file actually exists!

**Comment by nyrosmith** [comment]
@kentcdodds  Which one would you like next? Do you mind creating an issue per validator so that keeping track is easier?

**Comment by kentcdodds** [comment]
@nyrosmith, if you have interest and a second, why don't you just file an issue for the specific property you'd like to write a validator for and we can do it that way :-)

**Comment by kentcdodds** [comment]
Skeleton validators are now in place. Simply go to a file like [this](https://github.com/kentcdodds/webpack-validator/blob/535b3ea5ad9357dea17f31f35e22329074416b87/src/validators/devtool/index.js) and replace `noop` for a function which actually validates ([docs](https://github.com/kentcdodds/configuration-validator#validators)).

**Comment by nyrosmith** [comment]
After fixing the debug validator I'll start implementing output validators

**Comment by kentcdodds** [comment]
:+1:

**Comment by nyrosmith** [comment]
Can we close this and create new issues per webpack-config option?
Maybe beginner friendly tags could help too...

**Comment by kentcdodds** [comment]
> Can we close this and create new issues per webpack-config option?

Yes, that'd be easier to track

> Maybe beginner friendly tags could help too...

Agreed. I'd like to make a few of these [first-timers-only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issues as well...

I'm going to add you as a committer to the project if you don't mind. You're obviously motivated to contribute to this project :-) Please keep contributing via pull requests and I will too :-)

**Comment by nyrosmith** [comment]
I am very motivated :)
I really hope you don't regret adding me as a committer. I tend to mess up things while playing around and learning things

**Comment by kentcdodds** [comment]
That's great! As long as you do that in pull requests I don't mind at all :-)
