### ISSUE TITLE
Update npm dependencies & ReAdd npm-run-all

### ISSUE THREAD

**Issue by nyrosmith** [kentcdodds/webpack-validator#22]
We had to remove npm-run-all bc of [cross platform issues](https://github.com/kentcdodds/webpack-validator/pull/16)
This bug is fixed and I think it would be a good idea to update the deps & bring npm-run-all back

**Comment by nyrosmith** [comment]
@kentcdodds Maybe this is a good First-Timer issue?

**Comment by kentcdodds** [comment]
@nyrosmith totally! Want to make it? That'd be splendid!

**Comment by nyrosmith** [comment]
@kentcdodds It is not an urgent task so I thought maybe we find a new contributor. Then you have 2 new contributors to deal with :)
I think we need more labels & some discussion of what I am allowed to do in your repos and what's not ok

**Comment by kentcdodds** [comment]
Yeah, I should probably update the `CONTRIBUTING.md` with something... I'll give it some thought.

Basically:

1. Feel free to manage issues and PRs: open/close/label/etc.
2. Please don't commit directly to master, discuss in PRs and get someone else to hit the green merge button

I'll apply this same thing to myself as well :-)

**Comment by kentcdodds** [comment]
Also, yeah, we could probably use more labels. I added a `first-timers-only` label. Feel free to set this issue up for that and add the label :+1:

**Comment by kazekagegaara** [comment]
So you want to revert to https://github.com/kentcdodds/webpack-validator/commit/c06f18842e7679eb983915119c871ab0cacf5398 ? If that is all, then I can take this task up.

**Comment by kentcdodds** [comment]
@kazekagegaara pretty much. Just make sure that you get the latest version of `npm-run-all` :+1:

**Comment by nyrosmith** [comment]
Closed by https://github.com/kentcdodds/webpack-validator/pull/24
