### ISSUE TITLE
Add commitizen for commit conventions

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/webpack-validator#26]
Is that pending on purpose?

**Comment by jonathanewerner** [comment]
I wonder if works with the current beta status of the project? How can versions like 1.0.0-betaX be realized with the commit message release automation?

**Comment by kentcdodds** [comment]
Yeah, `semantic-release` wont work with `beta` AFAIK. So I'm holding off on adding it.

But that doesn't mean we shouldn't start following the standard. I've changed this issue title.

For an example of another repository that has commitizen well set up is: https://github.com/eggheadio-github/stack-overflow-copy-paste (notice the package.json and the badge)
