### ISSUE TITLE
Update entry to not check for file existance

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/webpack-validator#3]
From @sokra [on gitter](https://gitter.im/webpack/webpack?at=56c4229e5fa70a130ea50d91):

> @kentcdodds Looks good. The entry validator should not check for file existance, as the string is resolved, which means you can omit extension, add query parameters, add loaders, use modules paths. This is disallowed when checking of file existance.

Basically doing this validation thing is going to be really hard because Webpack is amazingly flexible.

**Comment by sapegin** [comment]
Maybe to check only if it’s a filename (contains an extension)?

**Comment by kentcdodds** [comment]
Ah, that's not a bad idea. Problem is many people often omit the extension because they rely on the [resolve.extensions](http://webpack.github.io/docs/configuration.html#resolve-extensions) (which we should probably account for here as well).

I want to err on the side of fewer errors I think, so unless we can think of a fool-proof way to know when to resort to checking for the file existing, I think I'll go for what you suggest.

**Comment by sapegin** [comment]
Yeah, `resolve.extensions` is a good idea also.
