### ISSUE TITLE
Replace import foo from '.' to import foo from './index'

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/webpack-validator#31]
Node 0.10 doesn't support the dot reference.

>>Looks like our first task after this gets merged is to update anywhere that we say: import foo from '.' to say: import foo from './index' because Node 0.10 doesn't support the dot reference.

>>Or maybe there's a babel plugin we could use (which would be sick). I wonder if there's a babel preset for Node 0.10. That would be a amazing...

Ideally this should be fixed before #30 can be merged.

**Comment by kentcdodds** [comment]
There are probably other things we'd need to do to support 0.10. I think even `configuration-validator` would need some changes.

**Comment by sarbbottam** [comment]
Could we treat `configuration-validator` separately, just for the ease of tracking, I am almost close to raise a PR for this :smile:

**Comment by kentcdodds** [comment]
Yeah, but if `configuration-validator` doesn't support Node 0.10 yet, this wont either ;-) More work to do I think. Thanks!

**Comment by sarbbottam** [comment]
Raised https://github.com/kentcdodds/configuration-validator/issues/11 to address the Node 0.10 issue in  `configuration-validator`
