### ISSUE TITLE
Replace path.parse with path-parse

### ISSUE THREAD

**Issue by jonathanewerner** [kentcdodds/webpack-validator#35]
### :octocat: Starter issue  
We would like to take the opportunity to invite someone who did not yet contribute to webpack-validator to work on this issue. Follow @YourFirstPR on Twitter for more of these issues across many open source projects :)

#### :bug: The Problem

We want to support node v0.10, where `path.parse` from the node standard library isn't yet available. So path.parse should be replaced by using the npm module [path-parse](https://npmjs.com/package/path-parse).

Steps:
- [x] Claim this issue (claimed by @miguelc1221)
- [ ] Follow setup instructions in [CONTRIBUTING.md](https://github.com/kentcdodds/webpack-validator/blob/master/CONTRIBUTING.md). [This course](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) might also be helpful to answer some questions that might arise. :)
- [ ] When you're set up, start by adding the needed dependency: `npm install --save path-parse`
- [ ] Open the file [`tests/passing-configs/index.js`](https://github.com/kentcdodds/webpack-validator/blob/f65af49b1b8181f13373d326d7771a9a90c7bdb0/tests/passing-configs/index.js), replace [`path.parse`](https://github.com/kentcdodds/webpack-validator/blob/f65af49b1b8181f13373d326d7771a9a90c7bdb0/tests/passing-configs/index.js#L17) with the function from the [`path-parse`](https://npmjs.com/package/path-parse) package (you'll need to install it by running `npm install --save-dev path-parse` and then import it at the top of the file).
- [ ] Commit and push changes to your branch. It doesn't have to be perfect, if tests don't pass, use the git flag `--no-verify` on your `git commit` and push to ask for help. 
- [ ]  You are done :clap:. Comment below that your pull request is ready for review.

**Comment by kentcdodds** [comment]
@jonathanewerner, please only add the `first-timers-only` label after the issue has been setup for a first timer (needs an extremely detailed checklist) :-)

**Comment by jonathanewerner** [comment]
Ok! :+1:

**Comment by miguelc1221** [comment]
working on it = )

**Comment by miguelc1221** [comment]
Sent pull request
