### ISSUE TITLE
flag issues as assigned if some one is working on it.

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/webpack-validator#37]
Could we assign the issues to individual, if they want to work on it and add a `assigned` flag, so that, whoever is free, can take up any `unassigned` issue.

Thoughts? / @kentcdodds @nyrosmith

**Comment by kentcdodds** [comment]
Sounds good to me.

**Comment by sarbbottam** [comment]
@kentcdodds Could you help tagging the issues, I guess it needs admin rights.

**Comment by nyrosmith** [comment]
Maybe we should just use Githubs "assign" mechanism?

**Comment by sarbbottam** [comment]
Yea, thats what I meant :smile:
