### ISSUE TITLE
Add more labels

### ISSUE THREAD

**Issue by nyrosmith** [kentcdodds/webpack-validator#38]
I think more labels could give us a better overview of the issues state. I propose "CLI" and "On Hold" as new labels.
Also everyone that picks an issue should assign himself or if insufficient rights he adds a comment that he picks it. This avoids unnecessary work as it happend to me yesterday.
Any thoughts?

**Comment by sarbbottam** [comment]
Suggested on similar line - https://github.com/kentcdodds/webpack-validator/issues/37

**Comment by jonathanewerner** [comment]
We should do this for sure.

**Comment by kentcdodds** [comment]
Hmmm... So even though you all have write access to the repo you can't:

- Create new labels
- Add/Remove labels to issues
- Assign issues

? That seems odd to me.

**Comment by jonathanewerner** [comment]
I can.

**Comment by kentcdodds** [comment]
Ok, cool. Feel free to do whatever you think needs to be done to help with the project. If there's a disagreement, I'll make the executive decision :-)

**Comment by nyrosmith** [comment]
I just didn't want to introduce new labels you might disagree. Sorry if I am too noisy

**Comment by kentcdodds** [comment]
Not at all! You're doing great! Thank you :-)
