### ISSUE TITLE
Check for invalid fields

### ISSUE THREAD

**Issue by xjamundx** [kentcdodds/webpack-validator#4]
I think the biggest thing you want to check if is people are using unsupported field names. This is true both at the root level and inside nested objects.

**Comment by kentcdodds** [comment]
If we get https://github.com/kentcdodds/configuration-validator/issues/1 supported, then all we need to do is create basic validators for at least every root property and that will cover us for now. Even something like:

```javascript
export default {
  key: 'devtool',
  validate() {}
}
```

Would be sufficient for now. Then we can go back through and fill in actual validation.

**Comment by kentcdodds** [comment]
This will be closed by #13
