### ISSUE TITLE
`resolve` validator

### ISSUE THREAD

**Issue by jonathanewerner** [kentcdodds/webpack-validator#48]
Implement validation for stuff configured in [`resolve`](https://webpack.github.io/docs/configuration.html#resolve).

**Comment by gdi2290** [comment]
can you add a validator for `resolve.root` to check that it's an absolute path and `resolve.modulesDirectories` has `node_modules`

**Comment by jonathanewerner** [comment]
Sure. :)

**Comment by jonathanewerner** [comment]
Have a look at #49.

**Comment by kentcdodds** [comment]
> resolve.modulesDirectories has node_modules

Note, it's not necessarily wrong to exclude node_modules. But we could return [a warning](https://github.com/kentcdodds/configuration-validator/blob/master/src/checkConfig/reformatResult/index.test.js#L51) in this case.

Though I would recommend that we'd need to figure out a way to disable validators or that would get really annoying for someone who knows what they're doing.

**Comment by gdi2290** [comment]
ya, I think we need a config file for webpack-validator (`webpack-validator.json') to make sure our webpack config file is valid 
![inception-briefcase-kOIbusN7fPnkk](https://camo.githubusercontent.com/92f15cb90b731c20a553b3afddba1de9ee4ed793/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f6b4f496275734e3766506e6b6b2f67697068792e676966)
