### ISSUE TITLE
Warns about webpack-hot-middleware

### ISSUE THREAD

**Issue by sapegin** [kentcdodds/webpack-validator#6]
In Webpack config:

```
entry: [
	'webpack-hot-middleware/client',
	path.join(__dirname, 'index');
],
```

Validation result:

```
entry: no file exists at /Users/tema/Dropbox/Projects/_Repos/react-styleguidist/webpack-hot-middleware/client - no file exists at /Users/tema/Dropbox/Projects/_Repos/react-styleguidist/src/index
```

**Comment by kentcdodds** [comment]
Hi @sapegin! Thanks for your interest in the project. This is a duplicate of #3...

I think that the real solution is to still check for the existence of a resolvable file, but only if the entry filename doesn't contain a query string or `webpack-hot-middleware` do you think that would cover all cases?

**Comment by kentcdodds** [comment]
Let's move discussion over to #3. Thanks!
