### ISSUE TITLE
#1 webpack gotcha: including `extensions` match `test`

### ISSUE THREAD

**Issue by gdi2290** [kentcdodds/webpack-validator#8]
validating that `extensions` match the regexp `test`

```es6
  resolve: {
    extensions: ['.js','.html']
  },

  module: {
    loaders: [
      { test: /\.html$/,  loader: 'raw-loader'}
    ]
  },
```

**Comment by kentcdodds** [comment]
Hmmm... Not sure this is a general enough use case to support. For example, I don't add `html` to my `extensions` and prefer to actually have the `.html` in the `import` statement.

**Comment by gdi2290** [comment]
ya, it's probably better to enforce devs to use the extensions

**Comment by kentcdodds** [comment]
But that's why I made this so pluggable. You can add it yourself! :-)

**Comment by gdi2290** [comment]
totes
