### ISSUE TITLE
`module` validator

### ISSUE THREAD

**Issue by gdi2290** [kentcdodds/webpack-validator#9]
`loaders` vs `loader` and when to use them

**Comment by kentcdodds** [comment]
:+1:

**Comment by jonathanewerner** [comment]
@gdi2290 Are you referring to [`loader`](http://webpack.github.io/docs/configuration.html#loader) vs. [`module.loaders`](http://webpack.github.io/docs/configuration.html#module-loaders)? 
It's not really clear to me how this "gotcha" could be expressed as an validation rule, apart from the existing spellchecking/whitelisting behaviour. Any thoughts?

**Comment by kentcdodds** [comment]
> apart from the existing spellchecking/whitelisting behaviour.

I think the spellchecking behavior will probably cover what @gdi2290 was talking about. I think we can probably close this. Please re-open if you disagree @gdi2290!

**Comment by gdi2290** [comment]
in webpack you can use both `loader` and `loaders` so devs would sometimes use an array for `loader`. Webpack 2 allows for TypeScript just as gulp does so this won't be a problem soon

**Comment by kentcdodds** [comment]
Ah yeah, so we need an actual validator for those before this can be closed.

**Comment by jonathanewerner** [comment]
I'm on this.

**Comment by jonathanewerner** [comment]
Tackled this in #47.
